# Bluestock Mutual Fund Analytics Capstone

Objective:
To analyse mutual fund performance, investor behaviour,
industry trends and risk metrics using Python,
SQLite and Power BI.

In [1]:
from pathlib import Path

raw_dir = Path("../data/raw")

print(raw_dir.exists())
print(list(raw_dir.glob("*.csv"))[:3])

True
[WindowsPath('../data/raw/01_fund_master.csv'), WindowsPath('../data/raw/02_nav_history.csv'), WindowsPath('../data/raw/03_aum_by_fund_house.csv')]

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

Load Datasets

In [3]:
raw_dir = Path("../data/raw")

fund_master = pd.read_csv(raw_dir/"01_fund_master.csv")
nav_history = pd.read_csv(raw_dir/"02_nav_history.csv")
aum = pd.read_csv(raw_dir/"03_aum_by_fund_house.csv")
sip = pd.read_csv(raw_dir/"04_monthly_sip_inflows.csv")
category = pd.read_csv(raw_dir/"05_category_inflows.csv")
folio = pd.read_csv(raw_dir/"06_industry_folio_count.csv")
performance = pd.read_csv(raw_dir/"07_scheme_performance.csv")
transactions = pd.read_csv(raw_dir/"08_investor_transactions.csv")
holdings = pd.read_csv(raw_dir/"09_portfolio_holdings.csv")
benchmark = pd.read_csv(raw_dir/"10_benchmark_indices.csv")

Dataset Shapes

In [4]:
datasets = {
    "Fund Master": fund_master,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Performance": performance,
    "Transactions": transactions,
    "Holdings": holdings,
    "Benchmark": benchmark
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

Fund Master: (40, 15)
NAV History: (46000, 3)
AUM: (90, 5)
SIP: (48, 6)
Category: (144, 3)
Folio: (21, 6)
Performance: (40, 19)
Transactions: (32778, 13)
Holdings: (322, 8)
Benchmark: (8050, 3)

Missing Values Check

In [5]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Fund Master
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

NAV History
amfi_code    0
date         0
nav          0
dtype: int64

AUM
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

SIP
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Category
month               0
category            0
net_inflow_crore    0
dtype: int64

Folio
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Performance
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Transactions
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Holdings
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Benchmark
date           0
index_name     0
close_value    0
dtype: int64

Data Types Check

In [6]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

Fund Master
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

NAV History
amfi_code      int64
date             str
nav          float64
dtype: object

AUM
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

SIP
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

Category
month                   str
category                str
net_inflow_crore    float64
dtype: object

Folio
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

Performance
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

Transactions
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

Holdings
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

Benchmark
date               str
index_name         str
close_value    float64
dtype: object

Sample Records

In [7]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [8]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

AMFI Validation

In [9]:
fund_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])

print(
    "Missing AMFI Codes:",
    len(fund_codes - nav_codes)
)

Missing AMFI Codes: 0

Markdown Conclusion

## Data Ingestion Summary

- Successfully loaded all 10 datasets
- Dataset dimensions verified
- Missing values identified
- Data types reviewed
- AMFI codes validated
- Data ready for cleaning and transformation